require("dotenv").config();
const express = require("express");
const nodemailer = require("nodemailer");
const cors = require("cors");

const app = express();
const PORT = process.env.PORT || 3000;

// ── Middleware ──────────────────────────────────────────────
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Serve static files (HTML, CSS, JS, assets) from root
app.use(express.static(__dirname));

// ── Nodemailer Transporter ──────────────────────────────────
const transporter = nodemailer.createTransport({
  service: "gmail", // change to "yahoo", "outlook", etc. if needed
  auth: {
    user: process.env.SENDER_EMAIL,   // your Gmail address
    pass: process.env.SENDER_PASS,    // your Gmail App Password
  },
});

// ── Contact Form Endpoint ───────────────────────────────────
app.post("/api/contact", async (req, res) => {
  const {
    fullName,
    companyName,
    phone,
    email,
    requirementType,
    product,
    quantity,
    message,
  } = req.body;

  // Basic validation
  if (!fullName || !email || !phone) {
    return res
      .status(400)
      .json({ success: false, error: "Name, email and phone are required." });
  }

  const mailOptions = {
    from: `"SS Coconuts Website" <${process.env.SENDER_EMAIL}>`,
    to: process.env.ADMIN_EMAIL,    // admin's inbox
    replyTo: email,                 // reply goes back to the client
    subject: `📦 New Enquiry from ${fullName} — SS Coconuts`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 12px; overflow: hidden;">

        <!-- Header -->
        <div style="background: #b8292f; padding: 24px 32px;">
          <h1 style="color: #fff; margin: 0; font-size: 20px; font-weight: 700;">New Customer Enquiry</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 6px 0 0; font-size: 13px;">Submitted via sscoconuts.com contact form</p>
        </div>

        <!-- Body -->
        <div style="padding: 32px; background: #ffffff;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr style="background:#f9fafb;">
              <td style="padding: 10px 14px; font-weight: 700; color: #374151; width: 40%;">Full Name</td>
              <td style="padding: 10px 14px; color: #111827;">${fullName}</td>
            </tr>
            <tr>
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Company</td>
              <td style="padding: 10px 14px; color: #111827;">${companyName || "—"}</td>
            </tr>
            <tr style="background:#f9fafb;">
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Phone</td>
              <td style="padding: 10px 14px; color: #111827;">${phone}</td>
            </tr>
            <tr>
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Email</td>
              <td style="padding: 10px 14px;"><a href="mailto:${email}" style="color:#b8292f;">${email}</a></td>
            </tr>
            <tr style="background:#f9fafb;">
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Requirement Type</td>
              <td style="padding: 10px 14px; color: #111827;">${requirementType || "—"}</td>
            </tr>
            <tr>
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Product Required</td>
              <td style="padding: 10px 14px; color: #111827;">${product || "—"}</td>
            </tr>
            <tr style="background:#f9fafb;">
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Quantity</td>
              <td style="padding: 10px 14px; color: #111827;">${quantity || "—"}</td>
            </tr>
          </table>

          <!-- Message -->
          <div style="margin-top: 24px; padding: 16px; background: #f9fafb; border-left: 4px solid #b8292f; border-radius: 4px;">
            <p style="font-weight: 700; color: #374151; margin: 0 0 8px; font-size: 13px;">Message</p>
            <p style="color: #4b5563; margin: 0; font-size: 14px; line-height: 1.6;">${message || "No message provided."}</p>
          </div>
        </div>

        <!-- Footer -->
        <div style="background: #f3f4f6; padding: 16px 32px; text-align: center; font-size: 12px; color: #9ca3af;">
          This email was automatically generated by the SS Coconuts contact form.
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    return res.json({ success: true, message: "Your enquiry has been sent successfully!" });
  } catch (err) {
    console.error("❌ Mail error:", err.message);
    return res.status(500).json({ success: false, error: "Failed to send email. Please try again." });
  }
});

// ── Quote Popup Endpoint ────────────────────────────────────
app.post("/api/quote", async (req, res) => {
  const { name, phone, product, quantity } = req.body;

  if (!name || !phone) {
    return res.status(400).json({ success: false, error: "Name and phone are required." });
  }

  const mailOptions = {
    from: `"SS Coconuts Website" <${process.env.SENDER_EMAIL}>`,
    to: process.env.ADMIN_EMAIL,
    subject: `🌴 New Quote Request from ${name} — SS Coconuts`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 12px; overflow: hidden;">

        <!-- Header -->
        <div style="background: #b8292f; padding: 24px 32px;">
          <h1 style="color: #fff; margin: 0; font-size: 20px; font-weight: 700;">New Quote Request</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 6px 0 0; font-size: 13px;">Submitted via SS Coconuts popup form</p>
        </div>

        <!-- Body -->
        <div style="padding: 32px; background: #ffffff;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr style="background:#f9fafb;">
              <td style="padding: 10px 14px; font-weight: 700; color: #374151; width: 40%;">Full Name</td>
              <td style="padding: 10px 14px; color: #111827;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Phone</td>
              <td style="padding: 10px 14px; color: #111827;">${phone}</td>
            </tr>
            <tr style="background:#f9fafb;">
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Product Interest</td>
              <td style="padding: 10px 14px; color: #111827;">${product || "—"}</td>
            </tr>
            <tr>
              <td style="padding: 10px 14px; font-weight: 700; color: #374151;">Estimated Quantity</td>
              <td style="padding: 10px 14px; color: #111827;">${quantity || "—"}</td>
            </tr>
          </table>
        </div>

        <!-- Footer -->
        <div style="background: #f3f4f6; padding: 16px 32px; text-align: center; font-size: 12px; color: #9ca3af;">
          This email was automatically generated by the SS Coconuts quote popup form.
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    return res.json({ success: true, message: "Quote request sent successfully!" });
  } catch (err) {
    console.error("❌ Quote mail error:", err.message);
    return res.status(500).json({ success: false, error: "Failed to send. Please try again." });
  }
});

// ── Start Server ────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`✅ SS Coconuts server running at http://localhost:${PORT}`);
});
